# Tarea día 8
**Programación I**

## David Gabriel
## 15/01/2020

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [1]:
import numpy as np
filas = 3
columnas = 4
Coord = np.arange(filas*columnas)
a = np.random.choice(Coord,int(filas*columnas/2),replace=False)
A = np.zeros((filas*columnas))
A[a] = 1
A.resize((filas,columnas))
A

array([[1., 0., 1., 0.],
       [1., 0., 1., 1.],
       [0., 0., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [231]:
A = np.zeros((5,2))
B = np.ones((5,2))
#1
C = A.reshape((10,1))
D = B.reshape((10,1))
#2
np.dstack((C,D))
#3
A.resize(1,10)
B.resize(1,10)
np.concatenate((A,B),axis=0)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [8]:
def f(x):
    return 2*x[:,0,None]+3*x[:,1,None]+x[:,2,None]**2

#1
X = np.random.random((3,4))
f(X)

array([[1.34658881],
       [5.02613799],
       [4.41469931]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [13]:
Area = 50*50
n = 1000000
x = np.random.random(n)*50
y = np.random.random(n)*50
x1 = np.logical_and(15<x,x<35)
y1 = np.logical_and(15<y,y<35)
z  = np.logical_and(x1,y1)
suma = z.sum()
Area2 = Area*suma/n
print(Area2)

400.005


## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

## Problema 1

In [21]:
#1 np.empty: crea un array sin inicializar sus valores. 
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.64520984e+185]])

In [22]:
#2 np.zeros: crea un array donde todos los elementos son cero
np.zeros((1,3))

array([[0., 0., 0.]])

In [23]:
#3 np.ones: crea un array donde todos sus valores son uno
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [25]:
#4 np.arange: crea un array similar a range(). 
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
#5 np.linspace: crea un array similar a arange, en donde se especifica
# el intervalo
np.linspace(0,5,num=10)


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [36]:
#6. np.logspace: similar a linspace, pero con escala logaritmica
np.logspace(1,4, num = 4)

array([   10.,   100.,  1000., 10000.])

In [57]:
#7 np.meshgrid: recibe dos linspace y devuelve el set de coordenas 
# para su producto cartesiano
x = np.linspace(0,5,num=3)
y = np.linspace(0,5,num=4)

array([[0.        , 0.        , 0.        ],
       [1.66666667, 1.66666667, 1.66666667],
       [3.33333333, 3.33333333, 3.33333333],
       [5.        , 5.        , 5.        ]])

In [60]:
#8 astype: convierte los elemntos de un array en otro tipo
np.arange(5).astype('float64')

array([0., 1., 2., 3., 4.])

In [61]:
#9 reshape: cambia la forma en la que se presenta un array
np.zeros((2,1)).reshape((1,2))

array([[0., 0.]])

In [62]:
#10 resize: similar a reshape pero se afecta el objeto, no solo como se 
# representa
x = np.zeros((2,1))
x.resize((1,2))
x

array([[0., 0.]])

In [64]:
#11 T: transpone un una matriz
x = np.random.random((1,2))
x.T

array([[0.99904789],
       [0.67085205]])

In [84]:
#12 np.swapaxes: intercambia dos ejes en una matriz 
x,np.swapaxes(x,0,1)

(array([[0.99904789, 0.67085205]]), array([[0.99904789],
        [0.67085205]]))

In [92]:
#13 np.concatenate: une matrices a lo largo de un eje
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
#14 np.vstack: apila matrices verticalmente
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
#15 np.hstack: apila matrices horizontalmente
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]]).T
np.hstack((a,b))

array([[1, 2, 5],
       [3, 4, 6]])

In [99]:
#16 np.dstack: apila matrices a lo largo del eje z:
a = np.array([[1, 2]])
b = np.array([[5, 6]])
np.dstack((a,b))

array([[[1, 5],
        [2, 6]]])

In [100]:
#17 np.empty_like: matriz vacia con forma de otra
a = np.array([[1, 2]])
np.empty_like(a)

array([[1, 2]])

In [101]:
#18 np.zeros_like: matriz de ceros con forma de otra
a = np.array([[1, 2]])
np.zeros_like(a)

array([[0, 0]])

In [102]:
#19 np.ones_like: matriz de unos con forma de otra
a = np.array([[1, 2]])
np.ones_like(a)

array([[1, 1]])

In [105]:
#20 no.eye: matriz cuadrada de ceros con, unos en la diagonal 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
#21 np.full: matriz llena del valor deseado
np.full((2,3),'hola')

array([['hola', 'hola', 'hola'],
       ['hola', 'hola', 'hola']], dtype='<U4')

In [108]:
#22 np.asarray: convertir objeto en array
a= [1,2]
np.asarray(a)

array([1, 2])

In [109]:
#23 np.asmatrix: convertir objeto en una matriz
a= [1,2]
np.asmatrix(a)

matrix([[1, 2]])

In [110]:
#24 np.array: crear un array
np.array([1,2])

array([1, 2])

In [115]:
#25 np.fromstring: crear un array a partir de un string
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [116]:
#26 np.diag: obtiene los elementos de la diagonal de una matriz
a = np.array([[1,2],[3,4]])
np.diag(a)

array([1, 4])

In [119]:
#27 np.tri: matriz con unos en la diagonal y debajo
np.tri(3, 3, 0)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [126]:
#28 np.tril: obtiene los elemntos de la diagonal y abajo
a = np.random.random((3,3))
np.tril(a)

array([[0.82291237, 0.        , 0.        ],
       [0.2321006 , 0.94749042, 0.        ],
       [0.87478755, 0.81441396, 0.44680896]])

In [127]:
#29 np.triu: obtiene los elementos d ela diagonal y arriba
a = np.random.random((3,3))
np.triu(a)

array([[0.00153167, 0.38104967, 0.0856433 ],
       [0.        , 0.17770716, 0.6393899 ],
       [0.        , 0.        , 0.89806856]])

In [131]:
#30 np.copy: crea una copia de un array
a = np.array([[1,2],[3,4]])
b = np.copy(a)
b

array([[1, 2],
       [3, 4]])

In [132]:
#31 np.flip: invierte el orden a lo largo de un eje
a = np.array([[1,2],[3,4]])
np.flip(a,axis=0)

array([[3, 4],
       [1, 2]])

In [138]:
#32 np.rot90: rota una matriz 90 grados en un plano especificado por 
#dos ejes
a = np.array([[1,2],[3,4]])
np.rot90(a,axes=(1,0))

array([[3, 1],
       [4, 2]])

In [139]:
#33 np.flipud: invierte el orden a lo largo del eje y
a = np.array([[1,2],[3,4]])
np.flipud(a)

array([[3, 4],
       [1, 2]])

In [140]:
#34 np.fliplr: invierte el orden a lo largo del eje x
a = np.array([[1,2],[3,4]])
np.fliplr(a)

array([[2, 1],
       [4, 3]])

In [144]:
#35 np.delete: elimina elementos de un array
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
np.delete(a,1,0)

array([[1, 2, 3],
       [7, 8, 9]])

In [159]:
#36 np.insert: insertar un objeto en un array
a=np.array([1,2,3])
np.insert(a,1,10)

array([ 1, 10,  2,  3])

In [160]:
#37 np.append: agregar valores al final de un array
a = np.array([[1, 2, 3], [4, 5, 6]])
np.append(a, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
#38 np.unique: encuentra los valores unicos de un array
a = np.arange(5)
a = np.append(a,1)
np.unique(a)

array([0, 1, 2, 3, 4])

In [165]:
#39 np.trim_zeros: elimina los ceros del principio y/o final 
# de un array unidimensional
np.trim_zeros([0, 1, 2, 0])

[1, 2]

In [166]:
#40 np.asscalar: convierte una matriz de un objeto en escalar
a = np.array([1])
np.asscalar(a)

1

In [170]:
#41 np.asarray_chkfinite: revisa si hay NaNs o infinitos
a = [1, 2,0]
np.asarray_chkfinite(a)

array([1, 2, 0])

In [181]:
#42 np.require: crea un array que cumpla con ciertos requisitos
a = np.array([1.2,2,3])
b = np.require(a,dtype='int32')
b

array([1, 2, 3])

In [182]:
#43 np.char.add: crea la concatenacion de arrays de strings
a = np.array(['a','b'])
b = np.array(['c','d'])
np.char.add(a,b)

array(['ac', 'bd'], dtype='<U2')

In [184]:
#44 np.charr.multiply: multiplica un array de strings
a = np.array(['a','b'])
np.char.multiply(a,4)

array(['aaaa', 'bbbb'], dtype='<U4')

In [211]:
#45 np.char.encode: llama a str.encode para cada elemento del array
a = np.array(['a','b'])
np.char.encode(a)

array([b'a', b'b'], dtype='|S1')

In [213]:
#46 np.capitalize: capitaliza cada elemento de un array
a = np.array(['aa','bb','cc'])
np.char.capitalize(a)

array(['Aa', 'Bb', 'Cc'], dtype='<U2')

In [220]:
#47 np.expandtabs: reemplaza cada \t con un espacio 
a = np.array(['aa\t q','bb','cc'])
np.char.expandtabs(a)

array(['aa       q', 'bb', 'cc'], dtype='<U10')

In [223]:
#48 np.atleast_1d: convierte objetos para que tengan al menos 1 dimension
a = 3
np.atleast_1d(a)

array([3])

In [224]:
#49 np.atleast_2d: lo mismo pero en 2 dimensiones
a = [3,4]
np.atleast_2d(a)

array([[3, 4]])

In [225]:
#50 np.atleast_3d: lo mismo pero en 3 dimensions
a = 3
np.atleast_3d(a)

array([[[3]]])

In [229]:
#51 np.broadcast_to: realiza broadcast a un array a otra forma
a = np.array([2,3])
np.broadcast_to(a,(3,2))

array([[2, 3],
       [2, 3],
       [2, 3]])

In [235]:
#52 np.broadcast_arrays: hace broadcast de un array contra otro
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [237]:
#53 np.expand_dims: expande la dimension de un array
x = np.array([[1,2,3]])
np.expand_dims(x,axis=2)

array([[[1],
        [2],
        [3]]])

In [240]:
#54 np.squeeze: elimina una dimension de un array
x = np.array([[1,2,3]])
x = np.expand_dims(x,axis=2)
np.squeeze(x,axis=2)

array([[1, 2, 3]])

In [254]:
#55 np.asfortranarray: array en orden de memoria de fortran
x = np.arange(6).reshape(2,3)
y = np.asfortranarray(x)
x.flags['F'],y.flags['F']

(False, True)

In [259]:
#56 np.ascontiguousarray: array en orden de memoria C
x = np.arange(6).reshape(2,3)
y = np.asfortranarray(x)
z = np.ascontiguousarray(y)
y.flags['C'],z.flags['C']

(False, True)

In [262]:
#57 np.asfarray: retorna un array de floats
a = np.array([2,3])
np.asfarray(a)

array([2., 3.])

In [266]:
#58 np.block: crea una matriz de matrices en forma de bloque:
np.block([[np.eye(2)*2, np.zeros((2, 3))],[np.zeros((3, 2)), np.eye(3)*3]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [270]:
#59 np.split: parte un array en n partes.
x = np.arange(12)
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [271]:
#60 np.array_split: parte un array en n partes. funciona incluso
# si no son partes del mismo tamaño
x = np.arange(7)
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [275]:
#61 np.dsplit: separa un array a lo largo del eje z
x = np.array([1,2])
y = np.array([3,4])
z = np.dstack((x,y))
np.dsplit(z,2)

[array([[[1],
         [2]]]), array([[[3],
         [4]]])]

In [280]:
#62 np.hsplit: separa un array a lo largo del eje x
x = np.array([1,2])
y = np.array([3,4])
z = np.hstack((x,y))
np.hsplit(z,2)

[array([1, 2]), array([3, 4])]

In [281]:
#63 np.vsplit: separa un array a lo largo del eje y
x = np.array([1,2])
y = np.array([3,4])
z = np.vstack((x,y))
np.vsplit(z,2)

[array([[1, 2]]), array([[3, 4]])]

In [283]:
#64 np.tile: devuelve un array repetido n veces
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [294]:
#65 np.repeat: repite n veces cada elemento de un array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
np.repeat(a,2,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [295]:
#66 np.bitwise_and: opera AND elemento por elemento
x = np.array([[True,False],[True,False]])
y = np.array([[True,False],[False,False]])
np.bitwise_and(x,y)

array([[ True, False],
       [False, False]])

In [296]:
#67 np.bitwise_or: opera OR elemento por elemento
x = np.array([[True,False],[True,False]])
y = np.array([[True,False],[False,False]])
np.bitwise_or(x,y)

array([[ True, False],
       [ True, False]])

In [297]:
#68 np.bitwise_xor: opera XOR (exclusive OR) elemento por elemnto
x = np.array([[True,False],[True,False]])
y = np.array([[True,False],[False,False]])
np.bitwise_xor(x,y)

array([[False, False],
       [ True, False]])

In [298]:
#69 np.invert: invierte los valores de un array, elemento por elemento
x = np.array([[True,False],[True,False]])
np.invert(x)

array([[False,  True],
       [False,  True]])

In [301]:
#70 np.binary_repr: retorna la representacion binaria 
np.binary_repr(1875)

'11101010011'

In [302]:
#71 np.char.lower: retorna un array de strings en minusculas
A = np.array(['HoLa'])
np.char.lower(A)

array(['hola'], dtype='<U4')

In [303]:
#72 np.char.upper: retorna un array de strings en mayusculas
A = np.array([['HoLa'],['AmIgOs']])
np.char.upper(A)

array([['HOLA'],
       ['AMIGOS']], dtype='<U6')

In [307]:
#73 np.fromfunction: construye un array de acuerdo a una funcion
np.fromfunction(lambda x, y: x *y, (4,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

## Problema 2

In [373]:
#podemos cambiar de directorio si hay problema para encontrar
#el archivo
#import os
#os.chdir('C:\\Users\\IN_CAP02\\Desktop\\P1')


x = np.fromfunction(lambda x, y: x**2+y, (4,3), dtype=int)
y = np.arange(7)

#con save se guarda un array en formato .npy
#con savez se puede guardar mas de un array en formato .npz

np.save('array',x,y)
np.savez('array',x,y)
Q=np.load('array.npz')
W=np.load('array.npy')

In [374]:
Q.files #el archivo npz tiene mas de un array 

['arr_0', 'arr_1']

In [379]:
print(Q['arr_0'])
print('------------')
print(Q['arr_1'])

[[ 0  1  2]
 [ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]
------------
[0 1 2 3 4 5 6]


In [377]:
W

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

## Problema 3

In [389]:
#podemos cambiar de directorio si hay problema para encontrar
#el archivo
#import os
#os.chdir('C:\\Users\\IN_CAP02\\Desktop\\P1')


x = np.fromfunction(lambda x, y: x**2+y, (4,3), dtype=int)

#es importante especificar cual es el delimitador, tanto
#a la hora de guardar, como a la hora de abrir

np.savetxt('array.txt', x, delimiter=',')   
x

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [390]:
np.loadtxt('array.txt', delimiter=',')

array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 9., 10., 11.]])

## Problema 4

In [442]:
#Creamos un archivo .csv de acuerdo a las especificaciones.
#Los valores elegidos son aleatorios entre 1 y 6 (solo como ejemplo)
Ejemplo_header = 'x1,x2,x3,x4,x5,x6,y'
Ejemplo = np.random.randint(7,size=(6,7))
np.savetxt('array.csv',Ejemplo, delimiter=',',header=Ejemplo_header)

#abrimos el archivo .csv
ARRAY=np.loadtxt('array.csv',delimiter=',')


In [443]:
#comprobamos que en efecto funcionó
Ejemplo

array([[1, 2, 4, 4, 6, 4, 4],
       [3, 6, 6, 3, 2, 3, 5],
       [4, 2, 4, 1, 5, 4, 3],
       [3, 1, 5, 1, 5, 5, 5],
       [2, 3, 5, 1, 2, 6, 4],
       [1, 3, 4, 5, 3, 2, 5]])

In [445]:
ARRAY

array([[1., 2., 4., 4., 6., 4., 4.],
       [3., 6., 6., 3., 2., 3., 5.],
       [4., 2., 4., 1., 5., 4., 3.],
       [3., 1., 5., 1., 5., 5., 5.],
       [2., 3., 5., 1., 2., 6., 4.],
       [1., 3., 4., 5., 3., 2., 5.]])

In [446]:
# asignamos X y y
X,y = ARRAY[:,:6],ARRAY[:,6]

In [447]:
X

array([[1., 2., 4., 4., 6., 4.],
       [3., 6., 6., 3., 2., 3.],
       [4., 2., 4., 1., 5., 4.],
       [3., 1., 5., 1., 5., 5.],
       [2., 3., 5., 1., 2., 6.],
       [1., 3., 4., 5., 3., 2.]])

In [448]:
y

array([4., 5., 3., 5., 4., 5.])

In [453]:
#resolvemos por linalg.solve
betas = np.linalg.solve(X,y)

In [454]:
betas

array([ 0.04575163, -0.75163399,  1.53921569,  0.46732026, -0.26470588,
       -0.24509804])

In [455]:
# Comprobamos que la solucion es correcta en donde X.beta = y
np.round(np.dot(X,betas))

array([4., 5., 3., 5., 4., 5.])